version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./landing_page/html:/usr/share/nginx/html
    network_mode: "bridge"
    ports:
      - "80:80"
    restart: always
  kiwix:
    image: ghcr.io/kiwix/kiwix-serve
    command: 'wikipedia_content.zim'
    volumes:
      - "./kiwix/content:/data"
    network_mode: "bridge"
    ports:
      - "8080:8080"
    restart: always
  kolibri:
    build:
      context: .
      dockerfile: kolibri/Dockerfile
    volumes:
      - "./kolibri/data:/root/.kolibri"
    network_mode: "bridge"
    ports:
      - "8888:8888"
      - "56789:56789"
    restart: always
