version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./landing_page/html:/usr/share/nginx/html
    ports:
      - "80:80"
    restart: always
  kiwix:
    image: ghcr.io/kiwix/kiwix-serve
    command: '/data/wikipedia_en_for_schools_maxi_2024-06.zim'
    volumes:
      - "./kiwix/content:/data"
    ports:
      - "8080:8080"
    restart: always
  kolibri:
    build:
      context: .
      dockerfile: kolibri/Dockerfile
    volumes:
      - "./kolibri/data:/root/.kolibri"
    ports:
      - "8888:8888"
      - "56789:56789"
    restart: always
  mariadb:
    image: docker.io/bitnami/mariadb:11.4
    container_name: mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
       - "3306:3306"
    restart: always
  moodle:
    image: docker.io/bitnami/moodle:latest
    ports:
      - '81:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    restart: always
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
