version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./landing_page/html:/usr/share/nginx/html
    ports:
      - "80:80"
  kiwix:
    image: kiwix/kiwix-serve
    command: 'wikipedia_en_100_nopic.zim'
    ports:
      - '8888:8080'
    volumes:
      - "./kiwix/content:/data"
  kolibri:
    build:
      context: .
      dockerfile: kolibri/Dockerfile
    ports:
      - '8080:8080'
