version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: landing_page/Dockerfile
    volumes:
      - ./landing_page/html:/var/www/html
    ports: 
      - "8080:80"
    networks:
      - internal
  php:
    image: php:fpm-alpine
    volumes:
      - ./landing_page/html:/var/www/html
    networks:
      - internal
networks:
  internal:
    driver: bridge

