version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./landing_page/html:/usr/share/nginx/html
    network_mode: "bridge"
    ports:
      - "80:80"
    restart: always
  kiwix:
    image: kiwix/kiwix-serve
    command: 'wikipedia_en_100_nopic.zim'
    volumes:
      - "./kiwix/content:/data"
    network_mode: "bridge"
    ports:
      - "8080:8080"
    restart: always
  kolibri:
    build:
      context: .
      dockerfile: kolibri/Dockerfile
    environment:
      - KOLIBRI_HTTP_PORT=8888
    network_mode: "bridge"
    ports:
      - "8888:8888"
    restart: always
